### ISSUE TITLE
Issue-doc

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/pro-sol2#28]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in accounts/create-system-account/native/package.json:
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by drone-1x** [comment]
I got it.
